// WARNING: This file is AUTOGENERATED!
// Edit version number in "version.template" file.

using System.Reflection;

[assembly: AssemblyVersion("1.9.3.313")]
[assembly: AssemblyFileVersion("1.9.3.313")]
[assembly: AssemblyInformationalVersion("1.9.3.313-local")]

#if FULL

namespace BuildInformation
{
    internal class Constants
    {
        internal static string BUILD_DATE
        {
            get
            {
                return "29052019"; // "01112015" - 1 november 2015
            }
        }
    }
}
#endif
